### ISSUE TITLE
cfdtx 需要京喜app环境

### ISSUE THREAD

**Issue by start0325** [LucaLin233/Luca_Conf#2]
这个提示怎么解，是从京喜app拿的token

**Comment by LucaLin233** [comment]
> 这个提示怎么解，是从京喜app拿的token

所以提示了什么。。

**Comment by start0325** [comment]
> 
> 
> > 这个提示怎么解，是从京喜app拿的token
> 
> 所以提示了什么。。

```
Apr 29 00:00:17 {
Apr 29 00:00:17 "iRet" : 4026,
Apr 29 00:00:17 "sErrMsg" : "需要京喜app环境"
Apr 29 00:00:17 }
```

**Comment by LucaLin233** [comment]
> > > 这个提示怎么解，是从京喜app拿的token
> > 
> > 
> > 所以提示了什么。。
> 
> ```
> Apr 29 00:00:17 {
> Apr 29 00:00:17 "iRet" : 4026,
> Apr 29 00:00:17 "sErrMsg" : "需要京喜app环境"
> Apr 29 00:00:17 }
> ```
安装了京喜app了吗，去京喜app抓一下京喜的ck看看

**Comment by start0325** [comment]
> 安装了京喜app了吗，去京喜app抓一下京喜的ck看看

我是用的 Docker，加入了调用的 `jdJxncTokens.js`，并按示例抓包和填入了token `{"farm_jstoken":"74**********0","timestamp":"1610******3","phoneid":"42c*****************4a0cf"}`

**Comment by LucaLin233** [comment]
> > 安装了京喜app了吗，去京喜app抓一下京喜的ck看看
> 
> 我是用的 Docker Nodejs模式，加入了调用的 `jdJxncTokens.js`，并按示例抓包和填入了token `{"farm_jstoken":"74**********0","timestamp":"1610******3","phoneid":"42c*****************4a0cf"}`

docker的话很抱歉没办法帮到你，我没折腾过docker，按理说给到京喜的token就能运行的，要不你还是用手机跑或者再问问其他人，这个脚本毕竟不是我做的，我只是上传了一下，原作者是whyour大佬

**Comment by start0325** [comment]
好的，那我再看看，感谢解答
